/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiffin.management.system;

import javax.swing.JOptionPane;
import tiffin.management.system.Conn.Connectionp;
import java.sql.PreparedStatement;
import java.sql.Connection;



/**
 *
 * @author Admin
 */
public class Subscription extends javax.swing.JFrame {
public String paymentmode;
   public String quantity;
  public String plan;
 public String startdate;
    /**
     * Creates new form Subscription
     */
    public Subscription() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboboxplan = new javax.swing.JComboBox<>();
        comboboxpaymentmode = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        spinnerstartdate = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txtamount = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboboxplan.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        comboboxplan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "One Day", "One Week", "One Month", "Three Month" }));
        comboboxplan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxplanActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 230, 40));

        comboboxpaymentmode.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        comboboxpaymentmode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Online" }));
        getContentPane().add(comboboxpaymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 230, 40));

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        jButton1.setText("Place Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 650, 230, 40));

        spinnerstartdate.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        spinnerstartdate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1698929820000L), new java.util.Date(1698929820000L), new java.util.Date(1701521820000L), java.util.Calendar.DAY_OF_MONTH));
        getContentPane().add(spinnerstartdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 230, 40));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel3.setText("Amount -");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        txtamount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtamount.setForeground(new java.awt.Color(0, 153, 153));
        txtamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 180, 40));

        txtquantity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantityActionPerformed(evt);
            }
        });
        txtquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtquantityKeyReleased(evt);
            }
        });
        getContentPane().add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 230, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("RS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 550, -1, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2023-10-12 070123.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1339, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         startdate = spinnerstartdate.getValue().toString();
         plan = (String) comboboxplan.getSelectedItem();
         quantity =  (String) txtquantity.getText();//spinnerquantity.getSelectedItem();
         paymentmode=  (String) comboboxpaymentmode.getSelectedItem();
                int qty = Integer.parseInt(quantity);

        
    if(startdate.equals("")){
        JOptionPane.showMessageDialog(null, "startdate is required."); 
    }else if(plan.equals("")){
        JOptionPane.showMessageDialog(null, "plan is required.");
    }else if(quantity.equals("")){
        JOptionPane.showMessageDialog(null, "quantity is required.");
    }else if(paymentmode.equals("")){
        JOptionPane.showMessageDialog(null, "payment mode is required.");
    }    else if(qty>10){
        JOptionPane.showMessageDialog(null, "Enter quantity till 10");
    }
    else {
        try{
            
            
            Connectionp connectionProvider = new Connectionp();
            Connection con = (Connection) connectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("insert into subscription(startdate,plan,quantity,paymentmode) values(?,?,?,?)");
            ps.setString(1, startdate);
            ps.setString(2, plan);
            ps.setString(3, quantity);
            ps.setString(4, paymentmode);
            ps.executeUpdate(); 
           


            
            JOptionPane.showMessageDialog(null, " order placed Successfully .");
            setVisible(false);
            new Subscription().setVisible(true);
            Payment payment = new Payment();
        payment.setVisible(true);
        this.dispose();
        } 
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }


        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboboxplanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxplanActionPerformed
        // TODO add your handling code here:
 
       
    }//GEN-LAST:event_comboboxplanActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void txtquantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquantityKeyReleased
        // TODO add your handling code here:
                int day1=100;
        int day7=650;
        int month=2500;
        int month3=6000;

        String quantity =  (String) txtquantity.getText();
        String plan =  (String) comboboxplan.getSelectedItem();
        int qty = Integer.parseInt(quantity);

        if(plan.equals("One Day")){
            if(!quantity.equals("")){
                int totalprice = qty * (day1);
                txtamount.setText(String.valueOf(totalprice));
            }
            else{
                txtamount.setText("");
            }

        }
        else if(plan.equals("One Week")){
            if(!quantity.equals("")){
                int totalprice = qty * (day7);
                txtamount.setText(String.valueOf(totalprice));
            }
            else{
                txtamount.setText("");
            }}
            else if (plan.equals("One Month")){
                if(!quantity.equals("")){
                    int totalprice = qty * (month);
                    txtamount.setText(String.valueOf(totalprice));
                }
                else{
                    txtamount.setText("");
                }}
                else if(plan.equals("Three Month")){
                    if(!quantity.equals("")){
                        int totalprice = qty * (month3);
                        txtamount.setText(String.valueOf(totalprice));
                    }
                    else{
                        txtamount.setText("");
                    }}
    }//GEN-LAST:event_txtquantityKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxpaymentmode;
    private javax.swing.JComboBox<String> comboboxplan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner spinnerstartdate;
    private javax.swing.JLabel txtamount;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
